FROM rust:1.94.0-slim-trixie

WORKDIR /app

RUN apt-get update && apt-get -y install zip libssl-dev pkg-config libglib2.0-dev
RUN apt-get -y install python3 python3-pip

RUN pip3 install --break-system-packages minio
RUN cargo init .

COPY Cargo.* ./

RUN cargo test --release --no-run

COPY . .
RUN chmod +x ./TESTING/run_tests.sh

CMD ["./TESTING/run_tests.sh"]
